apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: petclinic-deploy-stage
spec:
  params:
  - name: APP_CONFIG_GIT
    type: string
    description: The application configuration git repository
    default: https://github.com/siamaksade/spring-petclinic-config
  - name: APP_TESTS_GIT
    type: string
    description: The application test cases git repository
    default: https://github.com/siamaksade/spring-petclinic-gatling
  - name: APP_IMAGE_NAME
    type: string
    default: image-registry.openshift-image-registry.svc:5000/demo-dev/spring-petclinic
    description: The application image to deploy to stage
  - name: APP_IMAGE_TAG
    type: string
    default: "latest"
    description: The application image tag to deploy to stage
  - name: APP_IMAGE_DIGEST
    type: string
    default: ""
    description: The application image digest to deploy to stage
  - name: STAGE_NAMESPACE
    type: string
    default: demo-stage
    description: The namespace for Stage environments
  workspaces:
  - name: workspace
  tasks:
  - name: config-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    params:
    - name: url
      value: $(params.APP_CONFIG_GIT)
    - name: subdirectory
      value: spring-petclinic-config
    - name: deleteExisting
      value: "true"
  - name: tests-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: workspace
    runAfter:
      - config-clone
    params:
    - name: url
      value: $(params.APP_TESTS_GIT)
    - name: subdirectory
      value: spring-petclinic-gatling
    - name: deleteExisting
      value: "true"
  - name: deploy-stage
    taskRef:
      name: deploy-app
    runAfter:
      - config-clone
    params:
    - name: DEPLOYMENT_NAME
      value: spring-petclinic
    - name: CURRENT_IMAGE
      value: "quay.io/siamaksade/spring-petclinic:latest"
    - name: NEW_IMAGE_NAME
      value: $(params.APP_IMAGE_NAME)
    - name: NEW_IMAGE_TAG
      value: $(params.APP_IMAGE_TAG)
    - name: NEW_IMAGE_DIGEST
      value: $(params.APP_IMAGE_DIGEST)
    - name: NAMESPACE
      value: $(params.STAGE_NAMESPACE)
    - name: KUSTOMIZE_OVERLAY_DIR
      value: environments/stage
    workspaces:
    - name: source
      workspace: workspace
      subPath: spring-petclinic-config
  - name: test-stage
    taskRef:
      name: gatling
    runAfter:
      - deploy-stage
      - tests-clone
    params:
      - name: APP_URL
        value: "http://spring-petclinic.$(params.STAGE_NAMESPACE).svc.cluster.local:8080"
    workspaces:
    - name: simulations
      workspace: workspace
      subPath: spring-petclinic-gatling