---
apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjMmxoYldGcmMyRmtaU3QwWld0MGIyNDZORkZOU1V4SU9WZFdTRFZXV1RnMlRWSTNUazFGT1RBM1EwdEdVVXRPUlU1Uk1VUllTMUZSU0ZwWFdrdFlOelk1V2tNNFMwWklUMWN5UzBsVVR6UkdPUT09IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
imagePullSecrets:
- name: quay-push-secret
secrets:
- name: quay-push-secret
